# Generated by Django 4.2.7 on 2023-11-18 11:28

from django.db import migrations, models
import django.db.models.deletion
import imoveis.models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Situação')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('titulo', models.CharField(db_index=True, max_length=150)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='imoveis.categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Situação')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, max_length=100, verbose_name='Descrição')),
                ('imagem', stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to=imoveis.models.get_file_path, variations={'thumb': {'height': 1024, 'width': 1024}}, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Situação')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço')),
                ('imagem', stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to=imoveis.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name=imoveis.models.Imagem)),
                ('descricao', models.TextField(blank=True, max_length=1200, verbose_name='Descrição')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imoveis.categoria')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
            },
        ),
    ]
