# Generated by Django 4.2.7 on 2023-11-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_imovel_cidade_imovel_endereco_imovel_mobiliado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='area',
            field=models.PositiveSmallIntegerField(default='1', null=True, verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='bairro',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Bairro'),
        ),
    ]
