# Generated by Django 4.2.7 on 2023-11-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_imovel_area_imovel_bairro'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='banheiros',
            field=models.PositiveSmallIntegerField(default='1', null=True, verbose_name='Banheiros'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='elevador',
            field=models.PositiveSmallIntegerField(default='1', null=True, verbose_name='Elevador'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='quartos',
            field=models.PositiveSmallIntegerField(default='1', null=True, verbose_name='Quartos'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='suites',
            field=models.PositiveSmallIntegerField(default='1', null=True, verbose_name='Suítes'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='vagas_garagem',
            field=models.PositiveSmallIntegerField(default='1', null=True, verbose_name='Vagas na garagem'),
        ),
    ]
