# Generated by Django 4.2.4 on 2023-11-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0005_alter_imovel_elevador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagem',
            options={'verbose_name': 'Imagem', 'verbose_name_plural': 'Galeria de imagens'},
        ),
        migrations.AlterField(
            model_name='imovel',
            name='elevador',
            field=models.PositiveSmallIntegerField(default='1', null=True, verbose_name='Elevador'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='mobiliado',
            field=models.BooleanField(default=False, verbose_name='Mobiliado'),
        ),
    ]
