# Generated by Django 4.2.7 on 2023-12-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0008_imovel_google_map_imovel_video_yt'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='churrasqueira',
            field=models.PositiveSmallIntegerField(default='0', null=True, verbose_name='Churrasqueira'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='funcionarios',
            field=models.PositiveSmallIntegerField(default='0', null=True, verbose_name='Funcionários'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='lavanderia',
            field=models.PositiveSmallIntegerField(default='1', null=True, verbose_name='Lavanderia'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='pet',
            field=models.PositiveSmallIntegerField(default='0', null=True, verbose_name='Pode pet?'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='piscina',
            field=models.PositiveSmallIntegerField(default='0', null=True, verbose_name='Piscina'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='portaria24',
            field=models.PositiveSmallIntegerField(default='0', null=True, verbose_name='Portaria 24 hrs'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='zelador',
            field=models.PositiveSmallIntegerField(default='0', null=True, verbose_name='Zelador'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='elevador',
            field=models.PositiveSmallIntegerField(default='0', null=True, verbose_name='Elevador'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='suites',
            field=models.PositiveSmallIntegerField(default='0', null=True, verbose_name='Suítes'),
        ),
    ]
