# Generated by Django 4.2.4 on 2023-12-23 13:52

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imoveis.models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('cidade', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='Estado')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Situação')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('titulo', models.CharField(db_index=True, max_length=150)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='imoveis.categoria')),
            ],
            options={
                'verbose_name': 'Tipo do imóvel',
                'verbose_name_plural': 'Tipos de imóveis',
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Situação')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, max_length=100, verbose_name='Descrição')),
                ('imagem', stdimage.models.StdImageField(blank=True, upload_to=imoveis.models.get_file_path, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Galeria de imagens',
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Situação')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço')),
                ('imagem', stdimage.models.StdImageField(blank=True, upload_to=imoveis.models.get_file_path, verbose_name='Imagem')),
                ('descricao', models.TextField(blank=True, max_length=1200, verbose_name='Descrição')),
                ('endereco', models.CharField(blank=True, max_length=150, null=True, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cidade')),
                ('bairro', models.CharField(blank=True, max_length=150, null=True, verbose_name='Bairro')),
                ('uf', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='Estado')),
                ('area', models.PositiveSmallIntegerField(default='1', null=True, verbose_name='Área')),
                ('quartos', models.PositiveSmallIntegerField(default='1', null=True, verbose_name='Quartos')),
                ('banheiros', models.PositiveSmallIntegerField(default='1', null=True, verbose_name='Banheiros')),
                ('suites', models.PositiveSmallIntegerField(default='0', null=True, verbose_name='Suítes')),
                ('vagas_garagem', models.PositiveSmallIntegerField(default='1', null=True, verbose_name='Vagas na garagem')),
                ('elevador', models.PositiveSmallIntegerField(default='0', null=True, verbose_name='Elevador')),
                ('video_yt', models.TextField(blank=True, max_length=1200, verbose_name='Video')),
                ('google_map', models.TextField(blank=True, max_length=1200, verbose_name='Mapa')),
                ('funcionarios', models.PositiveSmallIntegerField(default='0', null=True, verbose_name='Funcionários')),
                ('mobiliado', models.BooleanField(default=False, verbose_name='Mobiliado')),
                ('churrasqueira', models.BooleanField(default=False, verbose_name='Churrasqueira')),
                ('piscina', models.BooleanField(default=False, verbose_name='Piscina')),
                ('lavanderia', models.BooleanField(default=False, verbose_name='Lavanderia')),
                ('portaria24', models.BooleanField(default=False, verbose_name='Portaria 24 hrs')),
                ('zelador', models.BooleanField(default=False, verbose_name='Zelador')),
                ('pet', models.BooleanField(default=False, verbose_name='Pode pet?')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imoveis.categoria')),
                ('galeria_imagens', models.ManyToManyField(blank=True, to='imoveis.imagem')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
            },
        ),
    ]
