# Generated by Django 4.2.7 on 2023-12-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0006_alter_imagem_options_alter_imovel_elevador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='galeria_imagens',
            field=models.ManyToManyField(blank=True, to='imoveis.imagem'),
        ),
    ]
