# Generated by Django 4.2.7 on 2023-12-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0007_imovel_galeria_imagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='google_map',
            field=models.TextField(blank=True, max_length=1200, verbose_name='Mapa'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='video_yt',
            field=models.TextField(blank=True, max_length=1200, verbose_name='Video'),
        ),
    ]
