# Generated by Django 4.2.7 on 2023-12-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0009_imovel_churrasqueira_imovel_funcionarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='churrasqueira',
            field=models.BooleanField(default=False, verbose_name='Churrasqueira'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='lavanderia',
            field=models.BooleanField(default=False, verbose_name='Lavanderia'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='pet',
            field=models.BooleanField(default=False, verbose_name='Pode pet?'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='piscina',
            field=models.BooleanField(default=False, verbose_name='Piscina'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='portaria24',
            field=models.BooleanField(default=False, verbose_name='Portaria 24 hrs'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='zelador',
            field=models.BooleanField(default=False, verbose_name='Zelador'),
        ),
    ]
